More work on temp project and some bookkeeping

diff --git a/temp/myc b/temp/myc
--- a/temp/myc
+++ b/temp/myc
@@ -12,9 +12,9 @@ get_couple() {
 ask_replace() {
     while :
     do
-        read -p "Would you like to replace this bookmark? (y/n)" answer
+        read -p "Would you like to replace this bookmark? (Y/n) :  " answer
         case $answer in
-            "y")
+            "Y")
                 echo "Overriding old [UNDESERVING] bookmark..."
                 return 0
                 ;;
@@ -31,7 +31,8 @@ m_add () {
     maybe_path=$2
     name_in_file=$(grep $name" ## " $te)
 
-    if [ -n "$name_in_file" ]; then # If length of string is nonzero
+    # Checks if the bookmark name is in bookmark file. If so, ask to override
+    if [[ -n "$name_in_file" ]]; then # If length of string is nonzero
         echo "This bookmark name already exists"
         echo "$name_in_file"
         ask_replace
@@ -40,29 +41,31 @@ m_add () {
         m_remove $name
     fi
   
-    if [ -z "$maybe_path" ]; then # If empty string
+    if [[ -z "$maybe_path" ]]; then # If empty string
         path=$PWD
     else
         temp_path=$PWD"/"$maybe_path # Making the path absolute
         # If path is a legit directory
-        if [ -d "$temp_path" ]; then
+        if [[ -d "$temp_path" ]]; then
             path=$temp_path
-        elif [ -d "$maybe_path" ]; then # it's already an absolute file path
+        elif [[ -d "$maybe_path" ]]; then # it's already an absolute file path
             path=$maybe_path
         else
-            echo "$maybe_path"" does not exist."
+            echo "$maybe_path"" does not exist or is not a directory."
             return 1
         fi
     fi
     
-    path_in_file=$(grep " ## ""$path"$  $te) # $ indicates EOL
-    if [ -n "$path_in_file" ]; then # If length of string is nonzero
-        echo "This path has already been bookmarked"
-        echo $path_in_file
-        ask_replace
-        [[ $? = 1 ]] && return 1 # 1 means no, 0 means yes
-        m_remove $path
-    fi
+    # Checks if the path is in bookmark file. If so, ask to override
+    # path_in_file=$(grep " ## ""$path"$  $te) # $ indicates EOL
+    # if [[ -n "$path_in_file" ]]; then # If length of string is nonzero
+    #     echo "This path has already been bookmarked"
+    #     echo $path_in_file
+    #     ask_replace
+    #     # $? is the exit code of the last function called
+    #     [[ $? = 1 ]] && return 1 # 1 means no, 0 means yes
+    #     m_remove $path
+    # fi
 
     echo $path" is now bookmarked to "$name
     echo $name" ## "$path >> $te
@@ -70,14 +73,15 @@ m_add () {
 }
 
 m_remove() {
+    # Notes: ^ indicates beginning of line
+    #        $ indicates end of line
     rem_this=$1
     echo "You are removing this bookmark: $rem_this..."
     if [[ -n $(grep ^"$rem_this"" ## " $te) ]]; then # it is a bookmark name
-        # sed "/^$rem_this ## /d" $te > $te
-        sed "/^$rem_this ## /d" $te
+        sed -i "/^$rem_this ## /d" $te
     elif [[ -n $(grep " ## ""$rem_this"$ $te) ]]; then # it is a file path
         echo "You are removing this bookmark: $rem_this"
-        sed "/ ## $rem_this$/d" $te > $te
+        sed -i "/ ## $rem_this$/d" $te
     else
         echo "$rem_this was not found in $te"
     fi
@@ -86,13 +90,13 @@ m_remove() {
 go_to() {
     bookmark=$1
     # EXAMPLE: couple_str = "bookmark_name ## /path/to/book/mark"
-    couple_str=$(grep $bookmark" ## " $te)
+    couple_str=$(grep ^"$bookmark"" ## " $te)
  
     # splits #couple_str by ' ## ' into array
     local IFS=" ## "
     read -ra couple <<< $couple_str
     go_path="${couple[1]}"
-    if [ -d $go_path ]; then # If path is a legit directory
+    if [[ -d $go_path ]]; then # If path is a legit directory
         cd "$go_path"
     else
         echo $go_path" does not exist."
@@ -100,8 +104,11 @@ go_to() {
 }
 
 list_all() {
-    cat $te
-    return
+    if [[ "$1" = "-s" ]]; then
+        cat $te | sort
+    else
+        cat $te
+    fi
 }
 
 myc() {
@@ -118,7 +125,7 @@ myc() {
             ;;
         "l")
             echo "Bookmarks:"
-            list_all
+            list_all $2
             ;;
         "")
             echo "got string?"
@@ -131,11 +138,13 @@ myc() {
 
 
 #TODO:
+# - change q l to q ls (better to avoid confusion)
 # - -l to list directories right after cd-ing there
 # - -f to find the path that a bookmark refers to
 # - -v to open vim on the path that a bookmark refers to
 # - -cv to change directory to the path and also open vim
 # - tab completion!
+# - have a thing to make the bookmark file
 # getopts!
 # rename to QUIRK!
 
